version: '3'
services:
  jenkins-to-aws:
    container_name: jenkins-aws
    image: jenkins/jenkins
    ports:
      - "8000:8000"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net

networks:
  net:
